[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "diffusion-homework"
version = "0.2.0"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["src"]