training:
  log_interval: 10
  run_name: "fashion_mnist"
  evaluation_metric: ''
  fid_eval_freq: 10
  fid_steps: 20
  fid_num_samples: 100
  checkpoint_freq: 10
  learning_rate: 0.0001
  num_epochs: 100
  
data:
  dataset_name: "FashionMNIST"
  data_root: "data"
  batch_size: 64
  num_workers: 4
  pin_memory: true

model:
  nb_channels: 64
  num_blocks: 4
  cond_channels: 64
  conditioned: False # Refers to noise (sigma) conditioning
  class_conditioned: False

diffusion:
  sigma_min: 0.002
  sigma_max: 80.0
